### ISSUE TITLE
Scroll when logging on terminal

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/Origami#13]
The focus of the demo web-page should be shifted to terminal if something is being printed on the terminal and then when the output is ready then focus can be shifted to output. The user can see the terminal log until the output is being processed.

**Comment by tocttou** [comment]
How will the UI work for this? Any idea?
The scroll to bottom approach currently used on cloudcv.org doesn't fit well here since the user can send text to terminal even after output has been processed.
Probably a show terminal window popup can be placed at the bottom right (similar to facebook chat but bigger in size).

**Comment by tocttou** [comment]
This is the UI I have in mind: 
1. http://i.imgur.com/vGvDAqi.png
2. http://i.imgur.com/m8OpN2I.png

**Comment by DESHRAJ** [comment]
I see. I will also try to build some UI mockups for the page. I will let you know soon.
