### ISSUE TITLE
Suppress warning logs in prettier 

### ISSUE THREAD

**Issue by vpn1997** [Cloud-CV/Origami#204]
- Currently we have prettier showing warnings and errors before webpack builds but it will be better if it only shows  error rather than  warnings .It will help in debugging errors easily. Otherwise we have to go through every warning  while finding  the errors.

**Comment by vpn1997** [comment]
- Hey shouldn't we config our package.json file such that whenever it builds , it  will run  `yarn run lint:fix` so 
 that it auto fixes most of the warnings and user will get only the errors and warning that requires attention.

**Comment by fristonio** [comment]
The idea does make sense but since currently origami runs lint test during build and exits if any errors are there leaving warnings as they are. Whenever we do a production build we should be certain that there are no lint errors and current implementation serves that purpose. I don't think that there should be any code changes while building so running a lint fix there is not the best way.
A better way here would be to add a **git hook** to commit and run eslint fix on that hook assuring that no commit is made without running a lint fix.

I don't have any strong opinions here though.

**Comment by vpn1997** [comment]
Pre commit hooks will also change the code before committing though. I dont think `link:fix` will have any code breaking changes , I tried adding `lint:fix` before `lint:watch test:watch` , it was working just fine .

**Comment by uttu357** [comment]
@vpn1997 @fristonio Running `lint:fix` on the build is not recommended as lint errors should be fixed before you build your final dist. Build is run on production and according to the flow there should be no styling errors while you build your final code. If there are still errors which are fixed at build, that implies that they are present in the remote codebase which defeats the purpose of linting code.  Use a pre-commit hook to run `lint:fix` and re-add the changed files there. Also showing warnings makes sense as those warnings are build errors and need to be fixed.
