### ISSUE TITLE
Add support for dialogue like interface

### ISSUE THREAD

**Issue by AvaisP** [Cloud-CV/Origami#79]
Users should be able to communicate back and forth with the demo. This is helpful for hosting demos for something like VQA

**Comment by vpn1997** [comment]
@AvaisP  hey i want to work on this issue, can you give some more insight.Like is this only specific to VQA  ?

**Comment by vpn1997** [comment]
Hey do you think we need to make any changes in origami lib for adding this feature?
As far as i can understand you want to cache the input(constant input) and then use the dialogue like interface to get the "variable input" (like question in VQA) .But there is only one method available for getting the text user input in origami lib.There should be a seperate method for getting the data from the dialoge like interface(or variable input). @AvaisP

**Comment by AvaisP** [comment]
@vpn1997 I'd suggest working on #78 before this as that involves almost completing changing the demo page. If you do this first, we'll need to do it again when we work on #78 
You're free to start working on #78. If you're interested, please leave a comment there and I'll assign the issue to you :smile:

**Comment by vpn1997** [comment]
@AvaisP Hey i would like to work on this. :smile:

**Comment by vpn1997** [comment]
@AvaisP  hey can you give some specifics on what exactly we want in 'dialogue like  interface'. :smile:

**Comment by deshraj** [comment]
@vpn1997: see this http://visualchatbot.cloudcv.org/ 

In this interface, the human can actually converse with an AI agent. We want something similar (remember that this is not the top priority as of now so I would recommend working on something else.)

**Comment by vpn1997** [comment]
@deshraj hey it was mentioned in the gsoc idea list(Deliverable) thats why i thought of picking this one.
:smile:

**Comment by deshraj** [comment]
I understand that. It will be time taking and hence we want to push it in the later part of GSoC. You might want to focus on other deliverables first. The project codebase is still evolving and we want to make the code even more robust, add more documentation, more unit tests etc. Just adding new features is of no use if we are not maintaining the codebase properly. :)

**Comment by vpn1997** [comment]
@deshraj hey just a small doubt.While i was working on this i saw origami-lib has functions for caching text and image arrays but while loading the arrays  _getUniqueCacheId()_ function requires same text and image array combination to produce the cacheId. Now suppose we want to cache the processed image features only and then use it with different text arrays (like in vqa) then we will run into some problems since it wont be able to generate the exact key that was used to cache the image feature array.
So i think there is a need to modify _getUniqueCacheId()_ function .Please correct me if i am wrong . :smile:
